spring:
  datasource:
    url: jdbc:h2:file:./dbfile/db
#    文件数据 ##jdbc:h2:mem:db #内存数据
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  # 项目contextPath，一般在正式发布版本中，我们不配置
  context-path: /mappingo
  # 错误页，指定发生错误时，跳转的URL。请查看BasicErrorController源码便知
  error:
    path: /error
  port: 8080
  session:
    timeout: 60